// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const DEFAULT_TEST_SUPABASE_URL = "https://example.supabase.co";
const DEFAULT_TEST_SUPABASE_KEY = "test-anon-key";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || DEFAULT_TEST_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || DEFAULT_TEST_SUPABASE_KEY;

const authStorage =
  typeof window !== "undefined" && window.sessionStorage
    ? window.sessionStorage
    : undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: authStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
