// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Capacitor } from '@capacitor/core';
import type { Database } from './types';

const FALLBACK_SUPABASE_PROJECT_ID = 'mjkcztedhfpavmdmzakj';
const FALLBACK_SUPABASE_URL = `https://${FALLBACK_SUPABASE_PROJECT_ID}.supabase.co`;
const FALLBACK_SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_kkwlHj0pHqPPCY4YHeVe6A_hG9Esjy5';

const PLACEHOLDER_PROJECT_IDS = new Set(['your-project-id', 'example']);
const PLACEHOLDER_SUPABASE_URLS = new Set([
  'https://example.supabase.co',
  'https://your-project-ref.supabase.co',
]);

function normalize(value: string | undefined) {
  return value?.trim();
}

function isPlaceholderProjectId(projectId: string | undefined) {
  if (!projectId) return true;
  return PLACEHOLDER_PROJECT_IDS.has(projectId.toLowerCase());
}

function isPlaceholderSupabaseUrl(url: string | undefined) {
  if (!url) return true;
  return PLACEHOLDER_SUPABASE_URLS.has(url.toLowerCase());
}

function isPlaceholderPublishableKey(key: string | undefined) {
  if (!key) return true;
  return key.toLowerCase().startsWith('your-');
}

const configuredProjectId = normalize(import.meta.env.VITE_SUPABASE_PROJECT_ID);
const configuredUrl = normalize(import.meta.env.VITE_SUPABASE_URL);
const configuredPublishableKey = normalize(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);

const derivedUrlFromProjectId =
  !isPlaceholderProjectId(configuredProjectId) && configuredProjectId
    ? `https://${configuredProjectId}.supabase.co`
    : undefined;

const SUPABASE_URL =
  !isPlaceholderSupabaseUrl(configuredUrl) && configuredUrl
    ? configuredUrl
    : derivedUrlFromProjectId || FALLBACK_SUPABASE_URL;

const SUPABASE_PUBLISHABLE_KEY =
  !isPlaceholderPublishableKey(configuredPublishableKey) && configuredPublishableKey
    ? configuredPublishableKey
    : FALLBACK_SUPABASE_PUBLISHABLE_KEY;

const usingFallbackCredentials =
  SUPABASE_URL === FALLBACK_SUPABASE_URL || SUPABASE_PUBLISHABLE_KEY === FALLBACK_SUPABASE_PUBLISHABLE_KEY;

if (usingFallbackCredentials) {
  const enforceConfig =
    import.meta.env.VITE_ENFORCE_SUPABASE_CONFIG === 'true';

  if (import.meta.env.PROD && enforceConfig) {
    throw new Error(
      'Missing Supabase runtime configuration. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY.'
    );
  }

  console.warn(
    `[supabase] Using fallback Supabase credentials${import.meta.env.PROD ? ' in production' : ' in local/dev'}. Configure VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY.`
  );
}

const authStorage =
  typeof window !== 'undefined'
    ? Capacitor.isNativePlatform()
      ? window.localStorage
      : window.sessionStorage
    : undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: authStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
